name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
          if [ "$BRANCH_NAME" = "develop" ]; then
            DEPLOY_DIR="/var/www/laravel/dandreez_dev"
          elif [ "$BRANCH_NAME" = "main" ]; then
            DEPLOY_DIR="/var/www/laravel/dandreez_app"
          else
            echo "Error: Unknown branch $BRANCH_NAME"
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no ubuntu@dandreez.dev-tugilo.com << EOF
            cd $DEPLOY_DIR
            git pull origin $BRANCH_NAME
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart apache2
          EOF